apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
