apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable during the rolling update
                         # https://blog.container-solutions.com/kubernetes-deployment-strategies
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ruanbekker/containers:nginx
        name: containers
        ports:
        - name: http
          containerPort: 80
        env:
        - name: OWNER
          value: "itsme"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
