---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret
  namespace: default
data:
  username: YWRtaW4=     # echo -n "admin"    | base64
  password: cGFzc3dvcmQ= # echo -n "password" | base64
