apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
  - name: jenkins
    port: 8080
    targetPort: 8080
  - name: jenkins-agent
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkinsci/blueocean:1.18.1
        name: jenkins
        ports:
        - containerPort: 8080
          name: jenkins
        - containerPort: 50000
          name: jenkins-agent
