apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
data:
  script.sh: |
    #!/bin/sh
    while true
    do 
      echo "test"
      sleep 1
    done
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - name: demo
      image: busybox
      command:
      - sh /app/script.sh
      volumeMounts:
      - name: config-volume
        mountPath: /app/script.sh
        subPath: script.sh
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never
